apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: what-the-helm
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/pratyushs93/argocd-poc.git
    targetRevision: HEAD
    path: templates
  destination:
    server: https://kubernetes.default.svc
    namespace: what-the-helm